bash test for existing folders

diff --git a/.github/workflows/distribute.yaml b/.github/workflows/distribute.yaml
--- a/.github/workflows/distribute.yaml
+++ b/.github/workflows/distribute.yaml
@@ -112,9 +112,8 @@ jobs:
 
       - if: matrix.os == 'windows-latest'
         name: Sirius Test
-        run: |
-          set dir=sirius_cli\src\test\temp_results\
-          if (exist %dir%) (echo "Found result directory %dir%...") else (echo "Error: result directory %dir% not found. Can not continue." && exit 1)
+        run: | 
+          if exist sirius_cli\src\test\temp_results\ (echo "Found result directory sirius_cli\src\test\temp_results\...") else (echo "Error: result directory sirius_cli\src\test\temp_results\ not found. Can not continue." && exit 1)
 
       - if: matrix.os != 'windows-latest'
         name: Sirius Test
