bash test for existing folders

diff --git a/.github/workflows/distribute.yaml b/.github/workflows/distribute.yaml
--- a/.github/workflows/distribute.yaml
+++ b/.github/workflows/distribute.yaml
@@ -115,10 +115,10 @@ jobs:
         run: |
           DIR="sirius_cli/src/test/temp_results"
           if ( -d "$DIR" )
-            echo "Found result directory ${DIR}..."
+            ( echo "Found result directory ${DIR}..." )
           else
-            echo "Error: ${DIR} not found. Can not continue."
-              exit 1
+            ( echo "Error: ${DIR} not found. Can not continue."
+              exit 1 )
 
       - if: matrix.os != 'windows-latest'
         name: Sirius Test
