bash test for existing folders

diff --git a/.github/workflows/distribute.yaml b/.github/workflows/distribute.yaml
--- a/.github/workflows/distribute.yaml
+++ b/.github/workflows/distribute.yaml
@@ -119,6 +119,16 @@ jobs:
           rm -r sirius_cli/src/test/temp_results
           ls sirius_cli/src/test
 
+      - name: Sirius Test
+        run: |
+          DIR="sirius_cli/src/test/temp_results"
+          if [ -d "$DIR" ]; then
+            echo "Found result directory ${DIR}..."
+          else
+            echo "Error: ${DIR} not found. Can not continue."
+              exit 1
+          fi
+
 
 #jobs:
 #  distCLI:
