windows bash try

diff --git a/.github/workflows/distribute.yaml b/.github/workflows/distribute.yaml
--- a/.github/workflows/distribute.yaml
+++ b/.github/workflows/distribute.yaml
@@ -113,14 +113,13 @@ jobs:
       - if: matrix.os == 'windows-latest'
         name: Sirius Test
         run: |
-          set dir=sirius_cli\src\test\temp_results\
-          echo %dir%
-          if exist %dir% ( 
-            echo Found result directory %dir%... 
-          ) else ( 
-            echo Error: result directory %dir% not found. Can not continue. 
-            exit 1 
-          ) 
+          DIR="sirius_cli/src/test/temp_results"
+          if [ -d "$DIR" ]; then
+            echo "Found result directory ${DIR}..."
+          else
+            echo "Error: result directory ${DIR} not found. Can not continue."
+              exit 1
+          fi 
           | bash
         shell: bash
 
