shortened code for sirius run

diff --git a/.github/workflows/distribute.yaml b/.github/workflows/distribute.yaml
--- a/.github/workflows/distribute.yaml
+++ b/.github/workflows/distribute.yaml
@@ -93,79 +93,16 @@ jobs:
           TXT_OUTPUT="${TEMP_DIR}/txt_temp_output"
           TXT_SUMMARY="${TEMP_DIR}/txt_temp_summary"
           case "$OSTYPE" in
-            darwin*)             
-              ./sirius_dist/sirius_cli_single_os/build/distributions/sirius.app/Contents/MacOS/sirius login --user-env SIRIUS_USER --password-env SIRIUS_PW
-              ./sirius_dist/sirius_cli_single_os/build/distributions/sirius.app/Contents/MacOS/sirius --input ${MGF_DATA} --output ${MGF_OUTPUT} formula -p orbitrap fingerprint structure compound-classes write-summaries --output ${MGF_SUMMARY}
-              ./sirius_dist/sirius_cli_single_os/build/distributions/sirius.app/Contents/MacOS/sirius -1 ${TXT_DATA_1} -2 ${TXT_DATA_2} -z 354.134704589844 -o ${TXT_OUTPUT} formula -p orbitrap write-summaries --output ${TXT_SUMMARY}
-              ./sirius_dist/sirius_cli_single_os/build/distributions/sirius.app/Contents/MacOS/sirius -o ${MS_OUTPUT} -i ${MS_DATA} --ignore-formula formula -p orbitrap -c 5 fingerprint structure compound-classes write-summaries --output ${MS_SUMMARY}
-            ;;
-            linux*)             
-              ./sirius_dist/sirius_cli_single_os/build/distributions/sirius/bin/sirius login --user-env SIRIUS_USER --password-env SIRIUS_PW
-              ./sirius_dist/sirius_cli_single_os/build/distributions/sirius/bin/sirius --input ${MGF_DATA} --output ${MGF_OUTPUT} formula -p orbitrap fingerprint structure compound-classes write-summaries --output ${MGF_SUMMARY}
-              ./sirius_dist/sirius_cli_single_os/build/distributions/sirius/bin/sirius -1 ${TXT_DATA_1} -2 ${TXT_DATA_2} -z 354.134704589844 -o ${TXT_OUTPUT} formula -p orbitrap write-summaries --output ${TXT_SUMMARY}
-              ./sirius_dist/sirius_cli_single_os/build/distributions/sirius/bin/sirius -o ${MS_OUTPUT} -i ${MS_DATA} --ignore-formula formula -p orbitrap -c 5 fingerprint structure compound-classes write-summaries --output ${MS_SUMMARY}
-            ;;
-            msys*)             
-              ./sirius_dist/sirius_cli_single_os/build/distributions/sirius/sirius.exe login --user-env SIRIUS_USER --password-env SIRIUS_PW
-              ./sirius_dist/sirius_cli_single_os/build/distributions/sirius/sirius.exe --input ${MGF_DATA} --output ${MGF_OUTPUT} formula -p orbitrap fingerprint structure compound-classes write-summaries --output ${MGF_SUMMARY}
-              ./sirius_dist/sirius_cli_single_os/build/distributions/sirius/sirius.exe -1 ${TXT_DATA_1} -2 ${TXT_DATA_2} -z 354.134704589844 -o ${TXT_OUTPUT} formula -p orbitrap write-summaries --output ${TXT_SUMMARY}
-              ./sirius_dist/sirius_cli_single_os/build/distributions/sirius/sirius.exe -o ${MS_OUTPUT} -i ${MS_DATA} --ignore-formula formula -p orbitrap -c 5 fingerprint structure compound-classes write-summaries --output ${MS_SUMMARY}
-            ;;
+            darwin*) SIRIUS="./sirius_dist/sirius_cli_single_os/build/distributions/sirius.app/Contents/MacOS/sirius" ;;
+            linux*) SIRIUS="./sirius_dist/sirius_cli_single_os/build/distributions/sirius/bin/sirius" ;;
+            msys*) SIRIUS="./sirius_dist/sirius_cli_single_os/build/distributions/sirius/sirius.exe" ;;
+            *) echo "Error: Could not find OS."; exit 1 ;;
           esac
+          ${SIRIUS} login --user-env SIRIUS_USER --password-env SIRIUS_PW
+          ${SIRIUS} --input ${MGF_DATA} --output ${MGF_OUTPUT} formula -p orbitrap fingerprint structure compound-classes write-summaries --output ${MGF_SUMMARY}
+          ${SIRIUS} -1 ${TXT_DATA_1} -2 ${TXT_DATA_2} -z 354.134704589844 -o ${TXT_OUTPUT} formula -p orbitrap write-summaries --output ${TXT_SUMMARY}
+          ${SIRIUS} -o ${MS_OUTPUT} -i ${MS_DATA} --ignore-formula formula -p orbitrap -c 5 fingerprint structure compound-classes write-summaries --output ${MS_SUMMARY}
         shell: bash
-
-#      - if: matrix.os == 'windows-latest'
-#        name: Sirius Windows Run
-#        run: |
-#          ./sirius_dist/sirius_cli_single_os/build/distributions/sirius/sirius.exe login --user-env SIRIUS_USER --password-env SIRIUS_PW
-#          ./sirius_dist/sirius_cli_single_os/build/distributions/sirius/sirius.exe --input ${MGF_DATA} --output ${MGF_OUTPUT} formula -p orbitrap fingerprint structure compound-classes write-summaries --output ${MGF_SUMMARY}
-#          ./sirius_dist/sirius_cli_single_os/build/distributions/sirius/sirius.exe -1 ${TXT_DATA_1} -2 ${TXT_DATA_2} -z 354.134704589844 -o ${TXT_OUTPUT} formula -p orbitrap write-summaries --output ${TXT_SUMMARY}
-#          ./sirius_dist/sirius_cli_single_os/build/distributions/sirius/sirius.exe -o ${MS_OUTPUT} -i ${MS_DATA} --ignore-formula formula -p orbitrap -c 5 fingerprint structure compound-classes write-summaries --output ${MS_SUMMARY}
-#        shell: bash
-#
-#      - if: matrix.os == 'ubuntu-latest'
-#        name: Sirius Ubuntu Run
-#        run: |
-#          TEMP_DIR="sirius_cli/src/test/temp_results"
-#          mkdir "${TEMP_DIR}" "${TEMP_DIR}/mgf_temp_output" "${TEMP_DIR}/mgf_temp_summary" "${TEMP_DIR}/ms_temp_output" "${TEMP_DIR}/ms_temp_summary" "${TEMP_DIR}/txt_temp_output" "${TEMP_DIR}/txt_temp_summary"
-#          DEMO_DIR="sirius_doc/manual/demo-data"
-#          MGF_DATA="${DEMO_DIR}/mgf/laudanosine.mgf"
-#          MS_DATA="${DEMO_DIR}/ms/Bicuculline.ms"
-#          TXT_DATA_1="${DEMO_DIR}/txt/chelidonine_ms.txt"
-#          TXT_DATA_2="${DEMO_DIR}/txt/chelidonine_msms1.txt,${DEMO_DIR}/txt/chelidonine_msms2.txt"
-#          MGF_OUTPUT="${TEMP_DIR}/mgf_temp_output"
-#          MGF_SUMMARY="${TEMP_DIR}/mgf_temp_summary"
-#          MS_OUTPUT="${TEMP_DIR}/ms_temp_output"
-#          MS_SUMMARY="${TEMP_DIR}/ms_temp_summary"
-#          TXT_OUTPUT="${TEMP_DIR}/txt_temp_output"
-#          TXT_SUMMARY="${TEMP_DIR}/txt_temp_summary"
-#          ./sirius_dist/sirius_cli_single_os/build/distributions/sirius/bin/sirius login --user-env SIRIUS_USER --password-env SIRIUS_PW
-#          ./sirius_dist/sirius_cli_single_os/build/distributions/sirius/bin/sirius --input ${MGF_DATA} --output ${MGF_OUTPUT} formula -p orbitrap fingerprint structure compound-classes write-summaries --output ${MGF_SUMMARY}
-#          ./sirius_dist/sirius_cli_single_os/build/distributions/sirius/bin/sirius -1 ${TXT_DATA_1} -2 ${TXT_DATA_2} -z 354.134704589844 -o ${TXT_OUTPUT} formula -p orbitrap write-summaries --output ${TXT_SUMMARY}
-#          ./sirius_dist/sirius_cli_single_os/build/distributions/sirius/bin/sirius -o ${MS_OUTPUT} -i ${MS_DATA} --ignore-formula formula -p orbitrap -c 5 fingerprint structure compound-classes write-summaries --output ${MS_SUMMARY}
-#        shell: bash
-#
-#      - if: matrix.os == 'macos-latest'
-#        name: Sirius MacOS Run
-#        run: |
-#          TEMP_DIR="sirius_cli/src/test/temp_results"
-#          mkdir "${TEMP_DIR}" "${TEMP_DIR}/mgf_temp_output" "${TEMP_DIR}/mgf_temp_summary" "${TEMP_DIR}/ms_temp_output" "${TEMP_DIR}/ms_temp_summary" "${TEMP_DIR}/txt_temp_output" "${TEMP_DIR}/txt_temp_summary"
-#          DEMO_DIR="sirius_doc/manual/demo-data"
-#          MGF_DATA="${DEMO_DIR}/mgf/laudanosine.mgf"
-#          MS_DATA="${DEMO_DIR}/ms/Bicuculline.ms"
-#          TXT_DATA_1="${DEMO_DIR}/txt/chelidonine_ms.txt"
-#          TXT_DATA_2="${DEMO_DIR}/txt/chelidonine_msms1.txt,${DEMO_DIR}/txt/chelidonine_msms2.txt"
-#          MGF_OUTPUT="${TEMP_DIR}/mgf_temp_output"
-#          MGF_SUMMARY="${TEMP_DIR}/mgf_temp_summary"
-#          MS_OUTPUT="${TEMP_DIR}/ms_temp_output"
-#          MS_SUMMARY="${TEMP_DIR}/ms_temp_summary"
-#          TXT_OUTPUT="${TEMP_DIR}/txt_temp_output"
-#          TXT_SUMMARY="${TEMP_DIR}/txt_temp_summary"
-#          ./sirius_dist/sirius_cli_single_os/build/distributions/sirius.app/Contents/MacOS/sirius login --user-env SIRIUS_USER --password-env SIRIUS_PW
-#          ./sirius_dist/sirius_cli_single_os/build/distributions/sirius.app/Contents/MacOS/sirius --input ${MGF_DATA} --output ${MGF_OUTPUT} formula -p orbitrap fingerprint structure compound-classes write-summaries --output ${MGF_SUMMARY}
-#          ./sirius_dist/sirius_cli_single_os/build/distributions/sirius.app/Contents/MacOS/sirius -1 ${TXT_DATA_1} -2 ${TXT_DATA_2} -z 354.134704589844 -o ${TXT_OUTPUT} formula -p orbitrap write-summaries --output ${TXT_SUMMARY}
-#          ./sirius_dist/sirius_cli_single_os/build/distributions/sirius.app/Contents/MacOS/sirius -o ${MS_OUTPUT} -i ${MS_DATA} --ignore-formula formula -p orbitrap -c 5 fingerprint structure compound-classes write-summaries --output ${MS_SUMMARY}
-#        shell: bash
 
       - name: Sirius MGF Test
         run: |
