bash test for existing folders

diff --git a/.github/workflows/distribute.yaml b/.github/workflows/distribute.yaml
--- a/.github/workflows/distribute.yaml
+++ b/.github/workflows/distribute.yaml
@@ -110,7 +110,18 @@ jobs:
           mkdir sirius_cli/src/test/temp_results/txt_temp_summary
           ./sirius_dist/sirius_cli_single_os/build/distributions/sirius.app/Contents/MacOS/sirius --help          ls sirius_cli/src/test
 
-      - name: Sirius Test
+      - if: matrix.os == 'windows-latest'
+        name: Sirius Test
+        run: |
+          DIR="sirius_cli/src/test/temp_results"
+          if ( -d "$DIR" )
+            echo "Found result directory ${DIR}..."
+          else
+            echo "Error: ${DIR} not found. Can not continue."
+              exit 1
+
+      - if: matrix.os != 'windows-latest'
+        name: Sirius Test
         run: |
           DIR="sirius_cli/src/test/temp_results"
           if [ -d "$DIR" ]; then
